backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "settings"
    label: "Impostazioni Sito"
    files:
      - label: "Configurazione Generale"
        name: "site"
        file: "_data/site.yml"
        fields:
          - {label: "Nome Sito", name: "title", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "text"}
          - {label: "URL Sito", name: "url", widget: "string"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - {label: "Immagine OG", name: "og_image", widget: "image"}
          - label: "Social Links"
            name: "social_links"
            widget: "list"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icona SVG", name: "icon", widget: "text"}
          
      - label: "Contenuti Sezioni"
        name: "content"
        file: "_data/content.yml"
        fields:
          - label: "Sezioni Alternate"
            name: "sections"
            widget: "list"
            max: 3
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Immagine", name: "image", widget: "image"}
              - {label: "Testo Alt Immagine", name: "image_alt", widget: "string"}
              - {label: "Icona SVG", name: "icon", widget: "text"}
              - label: "Paragrafi"
                name: "text"
                widget: "list"
                field: {label: "Paragrafo", name: "paragraph", widget: "text"}
          
      - label: "Galleria"
        name: "gallery"
        file: "_data/gallery.yml"
        fields:
          - {label: "Titolo Sezione", name: "title", widget: "string"}
          - {label: "Sottotitolo", name: "subtitle", widget: "text"}
          - label: "Immagini"
            name: "images"
            widget: "list"
            fields:
              - {label: "Immagine", name: "src", widget: "image"}
              - {label: "Descrizione", name: "alt", widget: "string"}
              
      - label: "Contatti"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "text"}
          - {label: "Email destinataria form", name: "form_email", widget: "string"}
          
      - label: "Citazione"
        name: "quote"
        file: "_data/quote.yml"
        fields:
          - {label: "Testo Citazione", name: "text", widget: "text"}
          
      - label: "Area Legale"
        name: "legal"
        file: "_data/legal.yml"
        fields:
          - label: "Sezioni Legali"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Contenuto", name: "content", widget: "text"}
